### ISSUE TITLE
colour bleed into log timstamps

### ISSUE THREAD

**Issue by ashak** [c-hudson/muddler#2]
If i have coloured output that's not reset, the next log line timestamp retains that colour

![image](https://github.com/user-attachments/assets/f4da9554-48f5-42f1-8462-9415e04e4e64)

**Comment by c-hudson** [comment]
This should be fixed in the latest commit. The logging function was taking the output from the world and writing verbatim. This should be fixed now.  Also, The ansi_init function did not protect against color bleeding but this may or may not have been seen as the ansi_substr() function might have corrected the issue dependent upon wrapping.
